### ISSUE TITLE
[Tracking] Research about this

### ISSUE THREAD

**Issue by cesaroll** [cesaroll/MS_LinQ_C_Sharp#1]
## TODO
- [x] Continue watching: https://youtu.be/KDUtjZHIx44
- [ ] Learn about tracking
- [ ] Learn About branching
- [ ] Learn about pulling requests

**Comment by cesaroll** [comment]
Closed
